export * from './answerPopUp/AnswerPopUp'
export * from './recordPopUp/RecordPopUp'
export * from './resultPopUp/ResultPopUp'
export * from './timePopUp/TimePopUp'
export * from './tutorialPopUp/TutorialPopUp'